export const nissanTemplate = [
  { codigo: 'BRPRT 70262', produto: 'Adaptador', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 11403', produto: 'Adesivo Coluna C Direita', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'BRPRT 11409', produto: 'Adesivo Coluna C Esquerda', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: '99098xA0A', produto: 'Adesivo L/D C PILLAR', modelo: 'Prototipo', cliente: 'Nissan' },
  { codigo: '99099xA0A', produto: 'Adesivo L/E C PILLAR', modelo: 'Prototipo', cliente: 'Nissan' },
  { codigo: 'BRPRT 11552', produto: 'Adesivo Prata', modelo: '220T', cliente: 'Nissan' },
  { codigo: 'BRPRT 11551', produto: 'Adesivo Preto', modelo: '220T', cliente: 'Nissan' },
  { codigo: 'BRPRT 11404', produto: 'Adesivo X Play P/mala', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'BRPRT 11130', produto: 'Aplique Grade Frontal TAG', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'NISS06', produto: 'Cabo Adaptador', modelo: 'Ariya', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11255', produto: 'Capota Maritima', modelo: 'Frontier', cliente: 'FROTA' },
  { codigo: 'BRPRT 11259', produto: 'Carregador Leaf', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 11273', produto: 'Carregador sem fio MY24', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'BRPRT 11273 NG', produto: 'Carregador sem fio MY24', modelo: 'Kicks', cliente: 'NISSAN' },
  { codigo: 'NISS01', produto: 'Etiqueta Bateria', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'DRPRT 70270', produto: 'Etiqueta carregador advert', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'DRPRT 70229', produto: 'Etiqueta Inmetro', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 70227', produto: 'Etiqueta Leaf', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BR01031578L', produto: 'Etiqueta Verde (Rotulagem)', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'NISS02', produto: 'Guia Rapido Leaf', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 11131', produto: 'Inserto Volante', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'BRPRT 11562', produto: 'Jogo Friso Lateral Vermelho', modelo: '-', cliente: 'Nissan' },
  { codigo: '63810-6MV0C', produto: 'Kit Fixação', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: 'DRPRT 50234', produto: 'Kit Manual', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 11555', produto: 'Kit Soleira - Kicks', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'BRPRT 11555 NG', produto: 'Kit Soleira - Kicks', modelo: 'Kicks', cliente: 'NISSAN' },
  { codigo: 'NISS03', produto: 'Manual Carregador Leaf', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'DRPRT 70263', produto: 'Mochila', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: '63810-6MV0A', produto: 'Para-Choque Direito', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: '63810-6MV0A NG', produto: 'Para-Choque Direito', modelo: 'Frontier', cliente: 'NISSAN' },
  { codigo: '63811-6MV0A', produto: 'Para-Choque Esquerdo', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: '63811-6MV0A NG', produto: 'Para-Choque Esquerdo', modelo: 'Frontier', cliente: 'NISSAN' },
  { codigo: '63810-6MV0B', produto: 'Para-Lama Dianteiro Direito', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: '63811-6MV0B', produto: 'Para-Lama Dianteiro Esquerdo', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: '63811-6MV0B NG', produto: 'Para-Lama Dianteiro Esquerdo', modelo: 'Frontier', cliente: 'NISSAN' },
  { codigo: '93828-6MV0A', produto: 'Para-Lama Traseiro Direito', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: '93828-6MV0A NG', produto: 'Para-Lama Traseiro Direito', modelo: 'Frontier', cliente: 'NISSAN' },
  { codigo: '93829-6MV0A', produto: 'Para-Lama Traseiro Esquerdo', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: '93829-6MV0A NG', produto: 'Para-Lama Traseiro Esquerdo', modelo: 'Frontier', cliente: 'NISSAN' },
  { codigo: '990795JJ0A', produto: 'Placa Ano de Fabricacao', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 11588', produto: 'Ponteira', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'NISS04', produto: 'Prisma', modelo: '-', cliente: 'Nissan' },
  { codigo: 'FRONTIER', produto: 'Prisma', modelo: '-', cliente: 'Nissan' },
  { codigo: 'NISS05', produto: 'Prisma', modelo: '-', cliente: 'Nissan' },
  { codigo: 'BRPRT 11357', produto: 'Protetor de Caçamba', modelo: 'Frontier', cliente: 'FROTA' },
  { codigo: 'BRPRT 11156', produto: 'Protetor de Carter', modelo: 'Kicks', cliente: 'FROTA' },
  { codigo: 'BRPRT 11359', produto: 'Rolo Insulfilm', modelo: '-', cliente: 'FROTA' },
  { codigo: 'k000453', produto: 'Soleira X-Play', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'KE7455500B', produto: 'Tapete', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 11055', produto: 'Tapete Carpete', modelo: 'Versa', cliente: 'Nissan' },
  { codigo: 'BRPRT 10753', produto: 'Tapete Frontier', modelo: 'Frontier', cliente: 'Nissan' },
  { codigo: 'BRPRT 10947', produto: 'Tapete PVC', modelo: 'Versa', cliente: 'Nissan' },
  { codigo: 'BRPRT 11326', produto: 'Tapete Sentra', modelo: 'Sentra', cliente: 'Nissan' },
  { codigo: 'BRPRT 11325', produto: 'Tapete X-PLAY', modelo: 'Kicks', cliente: 'Nissan' },
  { codigo: 'BRPRT 11355', produto: 'Trava de Estepe', modelo: 'Frontier', cliente: 'FROTA' },
  { codigo: 'BRPRT 11354', produto: 'Trava Rodas', modelo: '-', cliente: 'FROTA' },
  { codigo: 'BRPRT 70257', produto: 'Triângulo', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: '990799LH1A', produto: 'Vin Label', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'R100362098', produto: 'Vin Label', modelo: 'Leaf', cliente: 'Nissan' },
  { codigo: 'BRPRT 11605', produto: 'KIT Chicote Multimidia c/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11604', produto: 'KIT Chicote Multimidia s/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11607', produto: 'Moldura Multimidia c/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11608', produto: 'Moldura Multimidia s/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 3110100001', produto: 'Moldura Traseira', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11603', produto: 'Multimidia Pionner', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: '99098xA0A NG', produto: 'Adesivo L/D C PILLAR', modelo: 'Protopico', cliente: 'NISSAN' },
  { codigo: '99099xA0A NG', produto: 'Adesivo L/E C PILLAR', modelo: 'Protopico', cliente: 'NISSAN' },
  { codigo: 'NISSAN004', produto: 'Adesivo test drive', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11208', produto: 'Capota Maritima', modelo: 'Frontier', cliente: 'FROTA' },
  { codigo: 'T99E25MP0A', produto: 'Tapete Ariya', modelo: 'Ariya', cliente: 'FROTA' },
  { codigo: 'BRPRT11609', produto: 'Tampa USB', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'K000665', produto: 'KIT SOLEIRA -P02H', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'TEST002', produto: 'Adesivo test drive', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11591', produto: 'Aerofolio branco', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11566', produto: 'Jogo de Friso Branco', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'EL300BT', produto: 'Leitor Elgin Semm Fio', modelo: '-', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11605 NG', produto: 'KIT Chicote Multimidia c/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11604 NG', produto: 'KIT Chicote Multimidia s/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11607 NG', produto: 'Moldura Multimidia c/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11608 NG', produto: 'Moldura Multimidia s/ botao', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 3110100001 NG', produto: 'Moldura Traseira', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11603 NG', produto: 'Multimidia Pionner', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'NISSAN004 NG', produto: 'Adesivo test drive', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT11609 NG', produto: 'Tampa USB', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'K000665 NG', produto: 'KIT SOLEIRA -P02H', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'TEST002 NG', produto: 'Adesivo test drive', modelo: 'Kait', cliente: 'NISSAN' },
  { codigo: 'BRPRT 11591 NG', produto: 'Aerofolio branco', modelo: 'Kait', cliente: 'NISSAN' }
];

export const locadorasTemplate = [
  { codigo: 'BRG01', produto: 'Camera de Ré / Tartaruga', modelo: '-', cliente: 'Barigui' },
  { codigo: 'LOCAM4', produto: 'Bandeirola', modelo: '-', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM7', produto: 'Faixa Lado Direito', modelo: '-', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM6', produto: 'Faixa Lado Esquerdo', modelo: '-', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM9', produto: 'Forração Assoalho', modelo: '-', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM8', produto: 'Forração dos Bancos', modelo: '-', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM5', produto: 'Giroflex', modelo: '-', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM1', produto: 'Protetor de Caçamba', modelo: 'Frontier', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM2', produto: 'Santo Antonio', modelo: 'Frontier', cliente: 'Locações Americanas' },
  { codigo: 'LOCAM3', produto: 'Sirene Ré', modelo: '-', cliente: 'Locações Americanas' },
  { codigo: 'LOC01', produto: 'Apoio de Braço', modelo: 'Kicks', cliente: 'Localiza' },
  { codigo: 'LOC02', produto: 'Camera de Ré', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC03', produto: 'Capota de Fibra', modelo: 'Frontier', cliente: 'Localiza' },
  { codigo: 'LOC04', produto: 'Chicote de Ré', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC05', produto: 'Engate', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC06', produto: 'Etiqueta Decalque', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC07', produto: 'Modulo Engate', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC08', produto: 'Protetor de Caçamba', modelo: 'Frontier', cliente: 'Localiza' },
  { codigo: 'LOC09', produto: 'Protetor de Carter', modelo: 'kicks', cliente: 'Localiza' },
  { codigo: 'LOC010', produto: 'Sensor de Ré', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC012', produto: 'Sirene', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC013', produto: 'Tapete Porta-Malas', modelo: '-', cliente: 'Localiza' },
  { codigo: 'LOC014', produto: 'Trava de Estepe', modelo: 'Frontier', cliente: 'Localiza' },
  { codigo: 'LOC015', produto: 'Santo Antonio', modelo: 'Frontier', cliente: 'LOCALIZA' },
  { codigo: 'LOC016', produto: 'Capota Maritima', modelo: 'Frontier', cliente: 'LOCALIZA' },
  { codigo: 'LOC018', produto: 'Cofre', modelo: 'Kicks Play', cliente: 'LOCALIZA' },
  { codigo: 'LOC017', produto: 'Cofre', modelo: 'Novo kicks', cliente: 'LOCALIZA' },
  { codigo: 'MOV01', produto: 'Bagagito', modelo: 'Kicks', cliente: 'Movida' },
  { codigo: 'MOV02', produto: 'Protetor de Caçamba', modelo: 'Frontier', cliente: 'Movida' },
  { codigo: 'MOV03', produto: 'Protetor de Carter', modelo: '-', cliente: 'Movida' },
  { codigo: 'MOV04', produto: 'Adesivo QR Code', modelo: '-', cliente: 'Movida GTF' },
  { codigo: 'MOV05', produto: 'Adesivo I', modelo: '-', cliente: 'Movida RAC' },
  { codigo: 'MOV06', produto: 'Adesivo Para Brisa', modelo: '-', cliente: 'Movida RAC' },
  { codigo: 'MOV07', produto: 'Chaveiro', modelo: '-', cliente: 'Movida RAC' },
  { codigo: 'MOV08', produto: 'Lixeira', modelo: '-', cliente: 'Movida RAC' },
  { codigo: 'MOV09', produto: 'Porta Documento', modelo: '-', cliente: 'Movida RAC' },
  { codigo: 'MOV10', produto: 'Adesivo I', modelo: '-', cliente: 'Movida Zero KM' },
  { codigo: 'MOV11', produto: 'Adesivo Para Brisa', modelo: '-', cliente: 'Movida Zero KM' },
  { codigo: 'MOV12', produto: 'Etiqueta Decalque', modelo: '-', cliente: 'Movida Zero KM' },
  { codigo: 'MOV13', produto: 'Lixeira', modelo: '-', cliente: 'Movida Zero KM' },
  { codigo: 'SESE01', produto: 'Insulfilm Frontier', modelo: 'Frontier', cliente: 'SESE' },
  { codigo: 'SESE02', produto: 'Insulfilm Kicks', modelo: 'Kicks', cliente: 'SESE' },
  { codigo: 'SESE03', produto: 'Insulfilm Sentra', modelo: 'Sentra', cliente: 'SESE' },
  { codigo: 'SESE04', produto: 'Insulfilm Versa', modelo: 'Versa', cliente: 'SESE' },
  { codigo: 'SESE05', produto: 'Insulfilm P16', modelo: 'Novo Kicks', cliente: 'SESE' },
  { codigo: 'SESE06', produto: 'Insulfilm Antivandalismo', modelo: 'Kicks Play', cliente: 'SESE' },
  { codigo: 'SESE07', produto: 'Insulfilm Antivandalismo', modelo: 'Sentra', cliente: 'SESE' },
  { codigo: 'SESE09', produto: 'Insulfilm Antivandalismo', modelo: 'P16', cliente: 'SESE' },
  { codigo: 'SESE08', produto: 'Insulfilm Antivandalismo', modelo: 'Versa', cliente: 'SESE' },
  { codigo: 'SESE10', produto: 'Detergente Ypê', modelo: '-', cliente: 'SESE' },
  { codigo: 'SESE11', produto: 'Shampoo Jonhson', modelo: '-', cliente: 'SESE' },
  { codigo: 'UNI01', produto: 'Chaveiro', modelo: '-', cliente: 'Unidas' },
  { codigo: 'UNI02', produto: 'Lixeira', modelo: '-', cliente: 'Unidas' },
  { codigo: 'UNI03', produto: 'Porta Documento', modelo: '-', cliente: 'Unidas' },
  { codigo: 'UNI04', produto: 'Porta Manual', modelo: '-', cliente: 'Unidas' },
  { codigo: 'UNI05', produto: 'Sensor de Ré', modelo: '-', cliente: 'Unidas' },
  { codigo: 'LOC019', produto: 'ADESIVO GASOLINA', modelo: 'SENTRA ADVANCE', cliente: 'LOCALIZA' },
  { codigo: 'MOV14', produto: 'Manual do Condutor', modelo: '-', cliente: 'MOVIDA GTF' }
];
